# Generated by Django 4.2.9 on 2026-02-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_location_location_type_alter_location_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Stock mínimo'),
        ),
    ]
