# Generated by Django 4.2.9 on 2026-02-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_min_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('unit', 'Unidad'), ('kg', 'Kg'), ('lt', 'Lt'), ('cc', 'Cc')], default='unit', max_length=10, verbose_name='Unidad'),
        ),
    ]
