# Generated by Django 4.2.9 on 2026-02-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_default_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('SHELF', 'Estante'), ('BOX', 'Caja'), ('FURNITURE', 'Mueble'), ('FRIDGE', 'Refrigerador'), ('FREEZER', 'Congeladora'), ('OTHER', 'Otro')], default='OTHER', max_length=20, verbose_name='Tipo de ubicación'),
        ),
    ]
