# Generated by Django 4.2.9 on 2026-02-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('unit', 'Unidad'), ('kg', 'Kg'), ('lt', 'Lt'), ('cc', 'Cc'), ('gr', 'Gr')], default='unit', max_length=10, verbose_name='Unidad'),
        ),
    ]
