# Generated by Django 4.2.9 on 2026-02-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_batch_created_at_alter_batch_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('WASTE', 'Merma'), ('ADJUST', 'Ajuste')], max_length=10),
        ),
    ]
