# Generated by Django 4.2.9 on 2026-02-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_add_transfer_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('WASTE', 'Merma'), ('ADJUST', 'Ajuste'), ('TRANSFER', 'Traslado')], max_length=10, verbose_name='Tipo de movimiento'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='note',
            field=models.TextField(blank=True, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
    ]
